// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_MEMBER_VISITOR_H_
#define _BEHAVIAC_MEMBER_VISITOR_H_

#include "behaviac_agent_headers.h"

// Agent property and method handlers


namespace behaviac
{
	struct METHOD_TYPE_behaviac_TestAgent_SayHello { };
	template<> inline void TestAgent::_Execute_Method_<METHOD_TYPE_behaviac_TestAgent_SayHello>()
	{
		this->behaviac::TestAgent::SayHello();
	}

}

#endif // _BEHAVIAC_MEMBER_VISITOR_H_
